# Generated by Django 4.2.7 on 2025-11-03 11:11
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_auto_20251015_1044'),
        ('authentication', '0001_initial'),  # keep dependency but migration will reference legacy student table
    ]

    operations = [
        migrations.RunSQL(
            # Ensure FK constraints reference legacy student table
            sql="""
            DO $$
            DECLARE
                table_name TEXT;
                constraint_name TEXT;
                tables_to_fix TEXT[] := ARRAY[
                    'ai_study_plans',
                    'ai_generated_notes',
                    'manual_notes',
                    'ai_chat_history',
                    'ai_interaction_sessions',
                    'ai_favorites'
                ];
            BEGIN
                FOREACH table_name IN ARRAY tables_to_fix
                LOOP
                    constraint_name := table_name || '_student_id_fkey';

                    -- If constraint exists and points to something else, drop it
                    IF EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = constraint_name
                        AND conrelid = table_name::regclass
                    ) THEN
                        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', table_name, constraint_name);
                    END IF;

                    -- Create FK pointing to legacy student table (db_table = 'student')
                    EXECUTE format(
                        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE',
                        table_name,
                        constraint_name
                    );
                END LOOP;
            END $$;
            """,
            reverse_sql="""
            -- Reverse: drop created constraints (if exist)
            ALTER TABLE ai_study_plans DROP CONSTRAINT IF EXISTS ai_study_plans_student_id_fkey;
            ALTER TABLE ai_generated_notes DROP CONSTRAINT IF EXISTS ai_generated_notes_student_id_fkey;
            ALTER TABLE manual_notes DROP CONSTRAINT IF EXISTS manual_notes_student_id_fkey;
            ALTER TABLE ai_chat_history DROP CONSTRAINT IF EXISTS ai_chat_history_student_id_fkey;
            ALTER TABLE ai_interaction_sessions DROP CONSTRAINT IF EXISTS ai_interaction_sessions_student_id_fkey;
            ALTER TABLE ai_favorites DROP CONSTRAINT IF EXISTS ai_favorites_student_id_fkey;
            """
        ),
    ]
