FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY backend/ai_backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY backend/ai_backend /app

CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
